### ISSUE TITLE
java.io.FileNotFoundException: classifiers/all.3class.distsim.crf.ser.gz

### ISSUE THREAD

**Issue by lsarni** [flaxsearch/clade#2]
When I try to start the Stanford Named Entity Recognition server I get this error:
```
Exception in thread "main" java.io.FileNotFoundException: classifiers/all.3class.distsim.crf.ser.gz (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at edu.stanford.nlp.ie.AbstractSequenceClassifier.loadClassifier(AbstractSequenceClassifier.java:1362)
	at edu.stanford.nlp.ie.AbstractSequenceClassifier.loadClassifier(AbstractSequenceClassifier.java:1309)
	at edu.stanford.nlp.ie.crf.CRFClassifier.getClassifier(CRFClassifier.java:2296)
	at edu.stanford.nlp.ie.NERServer.main(NERServer.java:324)
```

That file isn't in the folder

**Comment by flaxsearch** [comment]
Hi, it's been a while since we worked on this project. There are some zip files in the https://github.com/flaxsearch/clade/tree/master/ folder which you may need to unzip to get this file installed.

**Comment by lsarni** [comment]
@flaxsearch Thanks, unzipping didn't change anything but I downloaded a newer version of the Stanford NER. Now I'm struggling getting an old version of Solr, since the new ones don't have the `example/solr`  folder

**Comment by epugh** [comment]
@lsarni check out PR #5 which deals with your NER classifier issue.  I'm going to update the Solr next...
