### ISSUE TITLE
Viewing the results without using the web interface

### ISSUE THREAD

**Issue by lsarni** [flaxsearch/clade#3]
Is it possible to view the results using the web interface?

I have created a taxonomy and classified some docx files but now I'm getting this error when I click on my taxonomy on the web:

```
Traceback (most recent call last):
  File "/Users/lucia/clade/lib/web/application.py", line 237, in process
    return self.handle()
  File "/Users/lucia/clade/lib/web/application.py", line 228, in handle
    return self._delegate(fn, self.fvars, args)
  File "/Users/lucia/clade/lib/web/application.py", line 409, in _delegate
    return handle_class(cls)
  File "/Users/lucia/clade/lib/web/application.py", line 385, in handle_class
    return tocall(*args)
  File "/Users/lucia/clade/server.py", line 106, in GET
    return json.dumps([taxes[tax_idx].for_jtree(_solr)])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 12: invalid start byte
```

I'm trying to figure out what's wrong but is there a way to access the results of the classification without the interface?

Since I'm using `docx` files, should I change something in the code to open them on the web app? I believe that might be the problem.

**Comment by lsarni** [comment]
I change the `json.dumps` encoding
